[package]
name = "hprof2db"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
jvm-hprof = "0.1.0"
memmap = "0.7.0"

[dependencies.rusqlite]
version = "0.29.0"
features = ["bundled"]
