[package]
name = "hprof2db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jvm-hprof = "0.1.0"
memmap = "0.7.0"
